<?php

/**
 * DO NOT EDIT!
 * This file was automatically generated via bin/generate-validator-spec.php.
 */

namespace AmpProject\Validator\Spec\Section;

use AmpProject\Attribute;
use AmpProject\Exception\InvalidSpecName;
use AmpProject\Extension;
use AmpProject\Format;
use AmpProject\Internal;
use AmpProject\Layout;
use AmpProject\Tag as Element;
use AmpProject\Validator\Spec\SpecRule;
use AmpProject\Validator\Spec\Tag;

final class Tags
{
    const TAGS = [
        'html doctype' => 'HtmlDoctype',
        'html doctype (AMP4ADS)' => 'HtmlDoctypeAmp4ads',
        'HTML' => 'Html',
        'html (transformed)' => 'HtmlTransformed',
        'HEAD' => 'Head',
        'title' => 'Title',
        'title [AMP4EMAIL]' => 'TitleAmp4email',
        'BASE' => 'Base',
        'link rel=' => 'LinkRel',
        'link rel=canonical' => 'LinkRelCanonical',
        'link rel=manifest' => 'LinkRelManifest',
        'link rel=preload' => 'LinkRelPreload',
        'link rel=stylesheet for fonts' => 'LinkRelStylesheetForFonts',
        'link itemprop=sameAs' => 'LinkItempropSameas',
        'link itemprop=' => 'LinkItemprop',
        'link property=' => 'LinkProperty',
        'meta charset=utf-8' => 'MetaCharsetUtf8',
        'meta name=viewport' => 'MetaNameViewport',
        'meta http-equiv=X-UA-Compatible' => 'MetaHttpEquivXUaCompatible',
        'meta name=apple-itunes-app' => 'MetaNameAppleItunesApp',
        'meta name=amp-experiments-opt-in' => 'MetaNameAmpExperimentsOptIn',
        'meta name=amp-3p-iframe-src' => 'MetaNameAmp3pIframeSrc',
        'meta name=amp-consent-blocking' => 'MetaNameAmpConsentBlocking',
        'meta name=amp-experiment-token' => 'MetaNameAmpExperimentToken',
        'meta name=amp-link-variable-allowed-origin' => 'MetaNameAmpLinkVariableAllowedOrigin',
        'meta name=amp-google-clientid-id-api' => 'MetaNameAmpGoogleClientidIdApi',
        'meta name=amp-ad-doubleclick-sra' => 'MetaNameAmpAdDoubleclickSra',
        'meta name=amp-list-load-more' => 'MetaNameAmpListLoadMore',
        'meta name=amp-recaptcha-input' => 'MetaNameAmpRecaptchaInput',
        'meta name=amp-script-src' => 'MetaNameAmpScriptSrc',
        'meta name=amp4ads-id' => 'MetaNameAmp4adsId',
        'meta name= and content=' => 'MetaNameAndContent',
        'meta http-equiv=Content-Type' => 'MetaHttpEquivContentType',
        'meta http-equiv=content-language' => 'MetaHttpEquivContentLanguage',
        'meta http-equiv=pics-label' => 'MetaHttpEquivPicsLabel',
        'meta http-equiv=imagetoolbar' => 'MetaHttpEquivImagetoolbar',
        'meta http-equiv=Content-Style-Type' => 'MetaHttpEquivContentStyleType',
        'meta http-equiv=Content-Script-Type' => 'MetaHttpEquivContentScriptType',
        'meta http-equiv=origin-trial' => 'MetaHttpEquivOriginTrial',
        'meta http-equiv=resource-type' => 'MetaHttpEquivResourceType',
        'meta http-equiv=x-dns-prefetch-control' => 'MetaHttpEquivXDnsPrefetchControl',
        'meta name=amp-ad-enable-refresh' => 'MetaNameAmpAdEnableRefresh',
        'meta name=amp-to-amp-navigation' => 'MetaNameAmpToAmpNavigation',
        'meta name=amp-cta-type' => 'MetaNameAmpCtaType',
        'meta name=amp-cta-url' => 'MetaNameAmpCtaUrl',
        'meta name=amp-cta-landing-page-type' => 'MetaNameAmpCtaLandingPageType',
        'meta name=amp4ads-vars-*' => 'MetaNameAmp4adsVars',
        'BODY' => 'Body',
        'ARTICLE' => 'Article',
        'SECTION' => 'Section',
        'section (AMP4EMAIL)' => 'SectionAmp4email',
        'NAV' => 'Nav',
        'ASIDE' => 'Aside',
        'H1' => 'H1',
        'H2' => 'H2',
        'H3' => 'H3',
        'H4' => 'H4',
        'H5' => 'H5',
        'H6' => 'H6',
        'HEADER' => 'Header',
        'FOOTER' => 'Footer',
        'ADDRESS' => 'Address',
        'P' => 'P',
        'HR' => 'Hr',
        'PRE' => 'Pre',
        'BLOCKQUOTE' => 'Blockquote',
        'OL' => 'Ol',
        'UL' => 'Ul',
        'LI' => 'Li',
        'DL' => 'Dl',
        'DT' => 'Dt',
        'DD' => 'Dd',
        'FIGURE' => 'Figure',
        'FIGCAPTION' => 'Figcaption',
        'DIV' => 'Div',
        'MAIN' => 'Main',
        'A' => 'A_',
        'A (AMP4EMAIL)' => 'AAmp4email',
        'EM' => 'Em',
        'STRONG' => 'Strong',
        'SMALL' => 'Small',
        'S' => 'S',
        'CITE' => 'Cite',
        'Q' => 'Q',
        'DFN' => 'Dfn',
        'ABBR' => 'Abbr',
        'DATA' => 'Data',
        'TIME' => 'Time',
        'CODE' => 'Code',
        'VAR' => 'Var',
        'SAMP' => 'Samp',
        'KBD' => 'Kbd',
        'SUB' => 'Sub',
        'SUP' => 'Sup',
        'I' => 'I',
        'B' => 'B',
        'U' => 'U',
        'MARK' => 'Mark',
        'RUBY' => 'Ruby',
        'RB' => 'Rb',
        'RT' => 'Rt',
        'RTC' => 'Rtc',
        'RP' => 'Rp',
        'BDI' => 'Bdi',
        'BDO' => 'Bdo',
        'SPAN' => 'Span',
        'BR' => 'Br',
        'WBR' => 'Wbr',
        'INS' => 'Ins',
        'DEL' => 'Del',
        'noscript > img' => 'NoscriptImg',
        'IFRAME' => 'Iframe',
        'VIDEO' => 'Video',
        'AUDIO' => 'Audio',
        'PICTURE' => 'Picture',
        'picture > source' => 'PictureSource',
        'amp-video > source' => 'AmpVideoSource',
        'amp-audio > source' => 'AmpAudioSource',
        'audio > source' => 'AudioSource',
        'video > source' => 'VideoSource',
        'amp-ima-video > source' => 'AmpImaVideoSource',
        'audio > track' => 'AudioTrack',
        'audio > track[kind=subtitles]' => 'AudioTrackKindSubtitles',
        'video > track' => 'VideoTrack',
        'video > track[kind=subtitles]' => 'VideoTrackKindSubtitles',
        'amp-audio > track' => 'AmpAudioTrack',
        'amp-audio > track[kind=subtitles]' => 'AmpAudioTrackKindSubtitles',
        'amp-video > track' => 'AmpVideoTrack',
        'amp-video > track[kind=subtitles]' => 'AmpVideoTrackKindSubtitles',
        'amp-ima-video > track' => 'AmpImaVideoTrack',
        'amp-ima-video > track[kind=subtitles]' => 'AmpImaVideoTrackKindSubtitles',
        'G' => 'G',
        'GLYPH' => 'Glyph',
        'GLYPHREF' => 'Glyphref',
        'IMAGE' => 'Image',
        'MARKER' => 'Marker',
        'METADATA' => 'Metadata',
        'PATH' => 'Path',
        'SOLIDCOLOR' => 'Solidcolor',
        'SVG' => 'Svg',
        'SWITCH' => 'Switch',
        'VIEW' => 'View',
        'CIRCLE' => 'Circle',
        'ELLIPSE' => 'Ellipse',
        'LINE' => 'Line',
        'POLYGON' => 'Polygon',
        'POLYLINE' => 'Polyline',
        'RECT' => 'Rect',
        'TEXT' => 'Text',
        'TEXTPATH' => 'Textpath',
        'TREF' => 'Tref',
        'TSPAN' => 'Tspan',
        'CLIPPATH' => 'Clippath',
        'FILTER' => 'Filter',
        'HKERN' => 'Hkern',
        'LINEARGRADIENT' => 'Lineargradient',
        'MASK' => 'Mask',
        'PATTERN' => 'Pattern',
        'RADIALGRADIENT' => 'Radialgradient',
        'lineargradient > stop' => 'LineargradientStop',
        'radialgradient > stop' => 'RadialgradientStop',
        'VKERN' => 'Vkern',
        'DEFS' => 'Defs',
        'SYMBOL' => 'Symbol',
        'USE' => 'Use',
        'FECOLORMATRIX' => 'Fecolormatrix',
        'FECOMPOSITE' => 'Fecomposite',
        'FEFLOOD' => 'Feflood',
        'FEGAUSSIANBLUR' => 'Fegaussianblur',
        'FEMERGE' => 'Femerge',
        'FEMERGENODE' => 'Femergenode',
        'FEOFFSET' => 'Feoffset',
        'DESC' => 'Desc',
        'svg title' => 'SvgTitle',
        'TABLE' => 'Table',
        'CAPTION' => 'Caption',
        'COLGROUP' => 'Colgroup',
        'COL' => 'Col',
        'TBODY' => 'Tbody',
        'THEAD' => 'Thead',
        'TFOOT' => 'Tfoot',
        'TR' => 'Tr',
        'TD' => 'Td',
        'TH' => 'Th',
        'FORM [method=GET]' => 'FormMethodGet',
        'FORM [method=POST]' => 'FormMethodPost',
        'FORM [method=GET] (AMP4EMAIL)' => 'FormMethodGetAmp4email',
        'FORM [method=POST] (AMP4EMAIL)' => 'FormMethodPostAmp4email',
        'FORM DIV [verify-error]' => 'FormDivVerifyError',
        'FORM DIV [verify-error][template]' => 'FormDivVerifyErrorTemplate',
        'FORM DIV [submitting]' => 'FormDivSubmitting',
        'FORM DIV [submitting][template]' => 'FormDivSubmittingTemplate',
        'FORM DIV [submit-success]' => 'FormDivSubmitSuccess',
        'FORM DIV [submit-success][template]' => 'FormDivSubmitSuccessTemplate',
        'FORM DIV [submit-error]' => 'FormDivSubmitError',
        'FORM DIV [submit-error][template]' => 'FormDivSubmitErrorTemplate',
        'LABEL' => 'Label',
        'INPUT' => 'Input',
        'INPUT [type=file]' => 'InputTypeFile',
        'INPUT [type=password]' => 'InputTypePassword',
        'BUTTON' => 'Button',
        'amp-app-banner button[open-button]' => 'AmpAppBannerButtonOpenButton',
        'SELECT' => 'Select',
        'DATALIST' => 'Datalist',
        'OPTGROUP' => 'Optgroup',
        'OPTION' => 'Option',
        'TEXTAREA' => 'Textarea',
        'OUTPUT' => 'Output',
        'PROGRESS' => 'Progress',
        'METER' => 'Meter',
        'FIELDSET' => 'Fieldset',
        'LEGEND' => 'Legend',
        'DETAILS' => 'Details',
        'SUMMARY' => 'Summary',
        'amphtml engine script' => 'AmphtmlEngineScript',
        'amphtml engine script (LTS)' => 'AmphtmlEngineScriptLts',
        'amphtml engine script [AMP4EMAIL]' => 'AmphtmlEngineScriptAmp4email',
        'amp4ads engine script' => 'Amp4adsEngineScript',
        'script type=application/ld+json' => 'ScriptTypeApplicationLdJson',
        'script id=amp-rtc' => 'ScriptIdAmpRtc',
        'amp-ima-video > script[type=application/json]' => 'AmpImaVideoScriptTypeApplicationJson',
        'noscript enclosure for boilerplate' => 'NoscriptEnclosureForBoilerplate',
        'noscript enclosure for boilerplate (transformed)' => 'NoscriptEnclosureForBoilerplateTransformed',
        'NOSCRIPT' => 'Noscript',
        'ACRONYM' => 'Acronym',
        'BIG' => 'Big',
        'CENTER' => 'Center',
        'DIR' => 'Dir',
        'HGROUP' => 'Hgroup',
        'LISTING' => 'Listing',
        'MULTICOL' => 'Multicol',
        'NEXTID' => 'Nextid',
        'NOBR' => 'Nobr',
        'SPACER' => 'Spacer',
        'STRIKE' => 'Strike',
        'TT' => 'Tt',
        'SLOT' => 'Slot',
        'O:P' => 'OP',
        'AMP-IMG' => 'AmpImg',
        'amp-img (transformed)' => 'AmpImgTransformed',
        'AMP-IMG (AMP4EMAIL)' => 'AmpImgAmp4email',
        'AMP-LAYOUT' => 'AmpLayout',
        'AMP-PIXEL' => 'AmpPixel',
        'I-AMPHTML-SIZER-RESPONSIVE' => 'IAmphtmlSizerResponsive',
        'I-AMPHTML-SIZER-INTRINSIC' => 'IAmphtmlSizerIntrinsic',
        'IMG-I-AMPHTML-INTRINSIC-SIZER' => 'ImgIAmphtmlIntrinsicSizer',
        'amp-img > img (transformed)' => 'AmpImgImgTransformed',
        'amp-img > img[placeholder] (transformed)' => 'AmpImgImgPlaceholderTransformed',
        'style amp-custom-length-check' => 'StyleAmpCustomLengthCheck',
        'style amp-custom' => 'StyleAmpCustom',
        'style amp-custom (AMP4ADS)' => 'StyleAmpCustomAmp4ads',
        'style amp-custom (AMP4EMAIL)' => 'StyleAmpCustomAmp4email',
        'style amp-custom (css-strict)' => 'StyleAmpCustomCssStrict',
        'head > style[amp-boilerplate]' => 'HeadStyleAmpBoilerplate',
        'head > style[amp-boilerplate] (transformed)' => 'HeadStyleAmpBoilerplateTransformed',
        'head > style[amp4ads-boilerplate]' => 'HeadStyleAmp4adsBoilerplate',
        'head > style[amp4email-boilerplate]' => 'HeadStyleAmp4emailBoilerplate',
        'noscript > style[amp-boilerplate]' => 'NoscriptStyleAmpBoilerplate',
        'noscript > style[amp-boilerplate] (transformed)' => 'NoscriptStyleAmpBoilerplateTransformed',
        'style[amp-keyframes]' => 'StyleAmpKeyframes',
        'style[amp-runtime] (transformed)' => 'StyleAmpRuntimeTransformed',
        'SCRIPT (amp-3d-gltf)' => 'ScriptAmp3dGltf',
        'AMP-3D-GLTF' => 'Amp3dGltf',
        'SCRIPT (amp-3q-player)' => 'ScriptAmp3qPlayer',
        'AMP-3Q-PLAYER' => 'Amp3qPlayer',
        'SCRIPT (amp-access-laterpay)' => 'ScriptAmpAccessLaterpay',
        'SCRIPT (amp-access-poool)' => 'ScriptAmpAccessPoool',
        'SCRIPT (amp-access-scroll)' => 'ScriptAmpAccessScroll',
        'SCRIPT (amp-access)' => 'ScriptAmpAccess',
        'amp-access extension .json script' => 'AmpAccessExtensionJsonScript',
        'SCRIPT (amp-accordion)' => 'ScriptAmpAccordion',
        'SCRIPT[custom-element=amp-accordion] (AMP4EMAIL)' => 'ScriptCustomElementAmpAccordionAmp4email',
        'AMP-ACCORDION' => 'AmpAccordion',
        'amp-accordion > section' => 'AmpAccordionSection',
        'SCRIPT (amp-action-macro)' => 'ScriptAmpActionMacro',
        'AMP-ACTION-MACRO' => 'AmpActionMacro',
        'SCRIPT (amp-ad-custom)' => 'ScriptAmpAdCustom',
        'AMP-AD-CUSTOM' => 'AmpAdCustom',
        'SCRIPT (amp-ad-exit)' => 'ScriptAmpAdExit',
        'AMP-AD-EXIT' => 'AmpAdExit',
        'amp-ad-exit configuration JSON' => 'AmpAdExitConfigurationJson',
        'amp-ad extension script' => 'AmpAdExtensionScript',
        'AMP-AD' => 'AmpAd',
        'amp-ad with type=custom' => 'AmpAdWithTypeCustom',
        'amp-ad with data-multi-size attribute' => 'AmpAdWithDataMultiSizeAttribute',
        'amp-ad with data-enable-refresh attribute' => 'AmpAdWithDataEnableRefreshAttribute',
        'AMP-EMBED' => 'AmpEmbed',
        'amp-embed with data-multi-size attribute' => 'AmpEmbedWithDataMultiSizeAttribute',
        'SCRIPT (amp-addthis)' => 'ScriptAmpAddthis',
        'AMP-ADDTHIS' => 'AmpAddthis',
        'SCRIPT (amp-analytics)' => 'ScriptAmpAnalytics',
        'amp-analytics extension .json script' => 'AmpAnalyticsExtensionJsonScript',
        'AMP-ANALYTICS' => 'AmpAnalytics',
        'SCRIPT (amp-anim)' => 'ScriptAmpAnim',
        'amp-anim extension script (AMP4EMAIL)' => 'AmpAnimExtensionScriptAmp4email',
        'AMP-ANIM' => 'AmpAnim',
        'AMP-ANIM (AMP4EMAIL)' => 'AmpAnimAmp4email',
        'SCRIPT (amp-animation)' => 'ScriptAmpAnimation',
        'amp-animation extension .json script' => 'AmpAnimationExtensionJsonScript',
        'AMP-ANIMATION' => 'AmpAnimation',
        'SCRIPT (amp-apester-media)' => 'ScriptAmpApesterMedia',
        'AMP-APESTER-MEDIA' => 'AmpApesterMedia',
        'SCRIPT (amp-app-banner)' => 'ScriptAmpAppBanner',
        'AMP-APP-BANNER' => 'AmpAppBanner',
        'SCRIPT (amp-audio)' => 'ScriptAmpAudio',
        'AMP-AUDIO' => 'AmpAudio',
        'amp-story >> amp-audio' => 'AmpStoryAmpAudio',
        'amp-audio (A4A)' => 'AmpAudioA4a',
        'SCRIPT (amp-auto-ads)' => 'ScriptAmpAutoAds',
        'AMP-AUTO-ADS' => 'AmpAutoAds',
        'SCRIPT (amp-autocomplete)' => 'ScriptAmpAutocomplete',
        'SCRIPT[custom-element=amp-autocomplete] (AMP4EMAIL)' => 'ScriptCustomElementAmpAutocompleteAmp4email',
        'amp-autocomplete' => 'AmpAutocomplete',
        'AMP-AUTOCOMPLETE (AMP4EMAIL)' => 'AmpAutocompleteAmp4email',
        'amp-autocomplete > input' => 'AmpAutocompleteInput',
        'amp-autocomplete JSON' => 'AmpAutocompleteJson',
        'SCRIPT (amp-base-carousel)' => 'ScriptAmpBaseCarousel',
        'AMP-BASE-CAROUSEL' => 'AmpBaseCarousel',
        'AMP-BASE-CAROUSEL [lightbox]' => 'AmpBaseCarouselLightbox',
        'AMP-BASE-CAROUSEL lightbox [lightbox-exclude]' => 'AmpBaseCarouselLightboxLightboxExclude',
        'AMP-BASE-CAROUSEL lightbox [child]' => 'AmpBaseCarouselLightboxChild',
        'SCRIPT (amp-beopinion)' => 'ScriptAmpBeopinion',
        'AMP-BEOPINION' => 'AmpBeopinion',
        'SCRIPT (amp-bind)' => 'ScriptAmpBind',
        'SCRIPT[custom-element=amp-bind] (AMP4EMAIL)' => 'ScriptCustomElementAmpBindAmp4email',
        'amp-bind extension .json script' => 'AmpBindExtensionJsonScript',
        'amp-state' => 'AmpState',
        'amp-state (AMP4EMAIL)' => 'AmpStateAmp4email',
        'AMP-BIND-MACRO' => 'AmpBindMacro',
        'SCRIPT (amp-bodymovin-animation)' => 'ScriptAmpBodymovinAnimation',
        'AMP-BODYMOVIN-ANIMATION' => 'AmpBodymovinAnimation',
        'SCRIPT (amp-brid-player)' => 'ScriptAmpBridPlayer',
        'AMP-BRID-PLAYER' => 'AmpBridPlayer',
        'SCRIPT (amp-brightcove)' => 'ScriptAmpBrightcove',
        'AMP-BRIGHTCOVE' => 'AmpBrightcove',
        'SCRIPT (amp-byside-content)' => 'ScriptAmpBysideContent',
        'AMP-BYSIDE-CONTENT' => 'AmpBysideContent',
        'SCRIPT (amp-call-tracking)' => 'ScriptAmpCallTracking',
        'AMP-CALL-TRACKING' => 'AmpCallTracking',
        'SCRIPT (amp-carousel)' => 'ScriptAmpCarousel',
        'SCRIPT[custom-element=amp-carousel] (AMP4EMAIL)' => 'ScriptCustomElementAmpCarouselAmp4email',
        'AMP-CAROUSEL' => 'AmpCarousel',
        'AMP-CAROUSEL lightbox' => 'AmpCarouselLightbox',
        'AMP-CAROUSEL lightbox [lightbox-exclude]' => 'AmpCarouselLightboxLightboxExclude',
        'AMP-CAROUSEL lightbox [child]' => 'AmpCarouselLightboxChild',
        'SCRIPT (amp-connatix-player)' => 'ScriptAmpConnatixPlayer',
        'AMP-CONNATIX-PLAYER' => 'AmpConnatixPlayer',
        'SCRIPT (amp-consent)' => 'ScriptAmpConsent',
        'amp-consent extension .json script' => 'AmpConsentExtensionJsonScript',
        'AMP-CONSENT' => 'AmpConsent',
        'amp-consent [type]' => 'AmpConsentType',
        'SCRIPT (amp-dailymotion)' => 'ScriptAmpDailymotion',
        'AMP-DAILYMOTION' => 'AmpDailymotion',
        'SCRIPT (amp-date-countdown)' => 'ScriptAmpDateCountdown',
        'AMP-DATE-COUNTDOWN' => 'AmpDateCountdown',
        'SCRIPT (amp-date-display)' => 'ScriptAmpDateDisplay',
        'AMP-DATE-DISPLAY' => 'AmpDateDisplay',
        'SCRIPT (amp-date-picker)' => 'ScriptAmpDatePicker',
        'amp-date-picker[type=single][mode=static]' => 'AmpDatePickerTypeSingleModeStatic',
        'amp-date-picker[type=single][mode=overlay]' => 'AmpDatePickerTypeSingleModeOverlay',
        'amp-date-picker[type=range][mode=static]' => 'AmpDatePickerTypeRangeModeStatic',
        'amp-date-picker[type=range][mode=overlay]' => 'AmpDatePickerTypeRangeModeOverlay',
        'amp-date-picker > template [date-template]' => 'AmpDatePickerTemplateDateTemplate',
        'amp-date-picker > template [info-template]' => 'AmpDatePickerTemplateInfoTemplate',
        'SCRIPT (amp-delight-player)' => 'ScriptAmpDelightPlayer',
        'AMP-DELIGHT-PLAYER' => 'AmpDelightPlayer',
        'SCRIPT (amp-dynamic-css-classes)' => 'ScriptAmpDynamicCssClasses',
        'SCRIPT (amp-embedly-card)' => 'ScriptAmpEmbedlyCard',
        'AMP-EMBEDLY-CARD' => 'AmpEmbedlyCard',
        'AMP-EMBEDLY-KEY' => 'AmpEmbedlyKey',
        'SCRIPT (amp-experiment)' => 'ScriptAmpExperiment',
        'amp-experiment extension .json script' => 'AmpExperimentExtensionJsonScript',
        'AMP-EXPERIMENT' => 'AmpExperiment',
        'SCRIPT (amp-facebook-comments)' => 'ScriptAmpFacebookComments',
        'AMP-FACEBOOK-COMMENTS' => 'AmpFacebookComments',
        'SCRIPT (amp-facebook-like)' => 'ScriptAmpFacebookLike',
        'AMP-FACEBOOK-LIKE' => 'AmpFacebookLike',
        'SCRIPT (amp-facebook-page)' => 'ScriptAmpFacebookPage',
        'AMP-FACEBOOK-PAGE' => 'AmpFacebookPage',
        'SCRIPT (amp-facebook)' => 'ScriptAmpFacebook',
        'AMP-FACEBOOK' => 'AmpFacebook',
        'SCRIPT (amp-fit-text)' => 'ScriptAmpFitText',
        'SCRIPT[custom-element=amp-fit-text] (AMP4EMAIL)' => 'ScriptCustomElementAmpFitTextAmp4email',
        'AMP-FIT-TEXT' => 'AmpFitText',
        'SCRIPT (amp-font)' => 'ScriptAmpFont',
        'AMP-FONT' => 'AmpFont',
        'SCRIPT (amp-form)' => 'ScriptAmpForm',
        'SCRIPT[custom-element=amp-form] (AMP4EMAIL)' => 'ScriptCustomElementAmpFormAmp4email',
        'SCRIPT (amp-fx-collection)' => 'ScriptAmpFxCollection',
        'SCRIPT (amp-fx-flying-carpet)' => 'ScriptAmpFxFlyingCarpet',
        'AMP-FX-FLYING-CARPET' => 'AmpFxFlyingCarpet',
        'SCRIPT (amp-geo)' => 'ScriptAmpGeo',
        'AMP-GEO' => 'AmpGeo',
        'amp-geo extension .json script' => 'AmpGeoExtensionJsonScript',
        'SCRIPT (amp-gfycat)' => 'ScriptAmpGfycat',
        'AMP-GFYCAT' => 'AmpGfycat',
        'SCRIPT (amp-gist)' => 'ScriptAmpGist',
        'AMP-GIST' => 'AmpGist',
        'SCRIPT (amp-google-document-embed)' => 'ScriptAmpGoogleDocumentEmbed',
        'AMP-GOOGLE-DOCUMENT-EMBED' => 'AmpGoogleDocumentEmbed',
        'SCRIPT (amp-gwd-animation)' => 'ScriptAmpGwdAnimation',
        'AMP-GWD-ANIMATION' => 'AmpGwdAnimation',
        'SCRIPT (amp-hulu)' => 'ScriptAmpHulu',
        'AMP-HULU' => 'AmpHulu',
        'SCRIPT (amp-iframe)' => 'ScriptAmpIframe',
        'AMP-IFRAME' => 'AmpIframe',
        'SCRIPT (amp-ima-video)' => 'ScriptAmpImaVideo',
        'AMP-IMA-VIDEO' => 'AmpImaVideo',
        'SCRIPT (amp-image-lightbox)' => 'ScriptAmpImageLightbox',
        'SCRIPT[custom-element=amp-image-lightbox] (AMP4EMAIL)' => 'ScriptCustomElementAmpImageLightboxAmp4email',
        'AMP-IMAGE-LIGHTBOX' => 'AmpImageLightbox',
        'SCRIPT (amp-image-slider)' => 'ScriptAmpImageSlider',
        'AMP-IMAGE-SLIDER' => 'AmpImageSlider',
        'amp-image-slider (transformed)' => 'AmpImageSliderTransformed',
        'AMP-IMAGE-SLIDER > DIV [first]' => 'AmpImageSliderDivFirst',
        'AMP-IMAGE-SLIDER > DIV [second]' => 'AmpImageSliderDivSecond',
        'SCRIPT (amp-imgur)' => 'ScriptAmpImgur',
        'AMP-IMGUR' => 'AmpImgur',
        'SCRIPT (amp-inline-gallery)' => 'ScriptAmpInlineGallery',
        'AMP-INLINE-GALLERY' => 'AmpInlineGallery',
        'amp-inline-gallery-pagination' => 'AmpInlineGalleryPagination',
        'amp-inline-gallery-pagination [inset]' => 'AmpInlineGalleryPaginationInset',
        'AMP-INLINE-GALLERY-THUMBNAILS' => 'AmpInlineGalleryThumbnails',
        'SCRIPT (amp-inputmask)' => 'ScriptAmpInputmask',
        'input [mask] (custom mask)' => 'InputMaskCustomMask',
        'input [mask=payment-card]' => 'InputMaskPaymentCard',
        'input [mask=date-dd-mm-yyyy]' => 'InputMaskDateDdMmYyyy',
        'input [mask=date-mm-dd-yyyy]' => 'InputMaskDateMmDdYyyy',
        'input [mask=date-mm-yy]' => 'InputMaskDateMmYy',
        'input [mask=date-yyyy-mm-dd]' => 'InputMaskDateYyyyMmDd',
        'SCRIPT (amp-instagram)' => 'ScriptAmpInstagram',
        'AMP-INSTAGRAM' => 'AmpInstagram',
        'SCRIPT (amp-install-serviceworker)' => 'ScriptAmpInstallServiceworker',
        'AMP-INSTALL-SERVICEWORKER' => 'AmpInstallServiceworker',
        'SCRIPT (amp-izlesene)' => 'ScriptAmpIzlesene',
        'AMP-IZLESENE' => 'AmpIzlesene',
        'SCRIPT (amp-jwplayer)' => 'ScriptAmpJwplayer',
        'AMP-JWPLAYER' => 'AmpJwplayer',
        'SCRIPT (amp-kaltura-player)' => 'ScriptAmpKalturaPlayer',
        'AMP-KALTURA-PLAYER' => 'AmpKalturaPlayer',
        'SCRIPT (amp-lightbox-gallery)' => 'ScriptAmpLightboxGallery',
        'SCRIPT (amp-lightbox)' => 'ScriptAmpLightbox',
        'SCRIPT[custom-element=amp-lightbox] (AMP4ADS)' => 'ScriptCustomElementAmpLightboxAmp4ads',
        'SCRIPT[custom-element=amp-lightbox] (AMP4EMAIL)' => 'ScriptCustomElementAmpLightboxAmp4email',
        'AMP-LIGHTBOX' => 'AmpLightbox',
        'amp-lightbox [AMP4ADS]' => 'AmpLightboxAmp4ads',
        'SCRIPT (amp-link-rewriter)' => 'ScriptAmpLinkRewriter',
        'amp-link-rewriter extension .json script' => 'AmpLinkRewriterExtensionJsonScript',
        'AMP-LINK-REWRITER' => 'AmpLinkRewriter',
        'SCRIPT (amp-list)' => 'ScriptAmpList',
        'SCRIPT[custom-element=amp-list] (AMP4EMAIL)' => 'ScriptCustomElementAmpListAmp4email',
        'AMP-LIST' => 'AmpList',
        'AMP-LIST DIV [fetch-error]' => 'AmpListDivFetchError',
        'AMP-LIST-LOAD-MORE' => 'AmpListLoadMore',
        'amp-list-load-more button[load-more-clickable]' => 'AmpListLoadMoreButtonLoadMoreClickable',
        'AMP-LIST (AMP4EMAIL)' => 'AmpListAmp4email',
        'SCRIPT (amp-live-list)' => 'ScriptAmpLiveList',
        'AMP-LIVE-LIST' => 'AmpLiveList',
        'AMP-LIVE-LIST [update]' => 'AmpLiveListUpdate',
        'AMP-LIVE-LIST [items]' => 'AmpLiveListItems',
        'AMP-LIVE-LIST [pagination]' => 'AmpLiveListPagination',
        'AMP-LIVE-LIST [items] item' => 'AmpLiveListItemsItem',
        'SCRIPT (amp-mathml)' => 'ScriptAmpMathml',
        'AMP-MATHML' => 'AmpMathml',
        'SCRIPT (amp-mega-menu)' => 'ScriptAmpMegaMenu',
        'AMP-MEGA-MENU' => 'AmpMegaMenu',
        'AMP-MEGA-MENU > NAV' => 'AmpMegaMenuNav',
        'AMP-MEGA-MENU > AMP-LIST' => 'AmpMegaMenuAmpList',
        'AMP-MEGA-MENU > AMP-LIST > TEMPLATE' => 'AmpMegaMenuAmpListTemplate',
        'AMP-MEGA-MENU NAV > UL/OL' => 'AmpMegaMenuNavUlOl',
        'AMP-MEGA-MENU NAV > UL/OL > LI' => 'AmpMegaMenuNavUlOlLi',
        'AMP-MEGA-MENU item-heading' => 'AmpMegaMenuItemHeading',
        'AMP-MEGA-MENU item-content' => 'AmpMegaMenuItemContent',
        'SCRIPT (amp-megaphone)' => 'ScriptAmpMegaphone',
        'amp-megaphone [data-playlist]' => 'AmpMegaphoneDataPlaylist',
        'amp-megaphone [data-episode]' => 'AmpMegaphoneDataEpisode',
        'SCRIPT (amp-minute-media-player)' => 'ScriptAmpMinuteMediaPlayer',
        'AMP-MINUTE-MEDIA-PLAYER' => 'AmpMinuteMediaPlayer',
        'SCRIPT (amp-mowplayer)' => 'ScriptAmpMowplayer',
        'AMP-MOWPLAYER' => 'AmpMowplayer',
        'SCRIPT (amp-mraid)' => 'ScriptAmpMraid',
        'SCRIPT (amp-mustache)' => 'ScriptAmpMustache',
        'SCRIPT[custom-template=amp-mustache] (AMP4ADS)' => 'ScriptCustomTemplateAmpMustacheAmp4ads',
        'SCRIPT[custom-template=amp-mustache] (AMP4EMAIL)' => 'ScriptCustomTemplateAmpMustacheAmp4email',
        'SCRIPT type=text/plain' => 'ScriptTypeTextPlain',
        'SCRIPT type=text/plain (AMP4EMAIL)' => 'ScriptTypeTextPlainAmp4email',
        'TEMPLATE' => 'Template',
        'TEMPLATE (AMP4EMAIL)' => 'TemplateAmp4email',
        'SCRIPT (amp-nested-menu)' => 'ScriptAmpNestedMenu',
        'AMP-NESTED-MENU' => 'AmpNestedMenu',
        'div amp-nested-menu' => 'DivAmpNestedMenu',
        'button amp-nested-menu' => 'ButtonAmpNestedMenu',
        'h2 amp-nested-menu' => 'H2AmpNestedMenu',
        'h3 amp-nested-menu' => 'H3AmpNestedMenu',
        'h4 amp-nested-menu' => 'H4AmpNestedMenu',
        'h5 amp-nested-menu' => 'H5AmpNestedMenu',
        'h6 amp-nested-menu' => 'H6AmpNestedMenu',
        'span amp-nested-menu' => 'SpanAmpNestedMenu',
        'SCRIPT (amp-next-page)' => 'ScriptAmpNextPage',
        'AMP-NEXT-PAGE > SCRIPT[type=application/json]' => 'AmpNextPageScriptTypeApplicationJson',
        'AMP-NEXT-PAGE > [separator]' => 'AmpNextPageSeparator',
        'AMP-NEXT-PAGE > [recommendation-box]' => 'AmpNextPageRecommendationBox',
        'AMP-NEXT-PAGE > [footer]' => 'AmpNextPageFooter',
        'amp-next-page with inline config' => 'AmpNextPageWithInlineConfig',
        'amp-next-page with src attribute' => 'AmpNextPageWithSrcAttribute',
        'amp-next-page [type=adsense]' => 'AmpNextPageTypeAdsense',
        'SCRIPT (amp-nexxtv-player)' => 'ScriptAmpNexxtvPlayer',
        'AMP-NEXXTV-PLAYER' => 'AmpNexxtvPlayer',
        'SCRIPT (amp-o2-player)' => 'ScriptAmpO2Player',
        'AMP-O2-PLAYER' => 'AmpO2Player',
        'SCRIPT (amp-onetap-google)' => 'ScriptAmpOnetapGoogle',
        'AMP-ONETAP-GOOGLE' => 'AmpOnetapGoogle',
        'SCRIPT (amp-ooyala-player)' => 'ScriptAmpOoyalaPlayer',
        'AMP-OOYALA-PLAYER' => 'AmpOoyalaPlayer',
        'SCRIPT (amp-orientation-observer)' => 'ScriptAmpOrientationObserver',
        'AMP-ORIENTATION-OBSERVER' => 'AmpOrientationObserver',
        'SCRIPT (amp-pan-zoom)' => 'ScriptAmpPanZoom',
        'AMP-PAN-ZOOM' => 'AmpPanZoom',
        'SCRIPT (amp-pinterest)' => 'ScriptAmpPinterest',
        'AMP-PINTEREST' => 'AmpPinterest',
        'SCRIPT (amp-playbuzz)' => 'ScriptAmpPlaybuzz',
        'AMP-PLAYBUZZ' => 'AmpPlaybuzz',
        'SCRIPT (amp-position-observer)' => 'ScriptAmpPositionObserver',
        'AMP-POSITION-OBSERVER' => 'AmpPositionObserver',
        'SCRIPT (amp-powr-player)' => 'ScriptAmpPowrPlayer',
        'AMP-POWR-PLAYER' => 'AmpPowrPlayer',
        'SCRIPT (amp-reach-player)' => 'ScriptAmpReachPlayer',
        'AMP-REACH-PLAYER' => 'AmpReachPlayer',
        'SCRIPT (amp-recaptcha-input)' => 'ScriptAmpRecaptchaInput',
        'AMP-RECAPTCHA-INPUT' => 'AmpRecaptchaInput',
        'SCRIPT (amp-redbull-player)' => 'ScriptAmpRedbullPlayer',
        'AMP-REDBULL-PLAYER' => 'AmpRedbullPlayer',
        'SCRIPT (amp-reddit)' => 'ScriptAmpReddit',
        'AMP-REDDIT' => 'AmpReddit',
        'SCRIPT (amp-riddle-quiz)' => 'ScriptAmpRiddleQuiz',
        'AMP-RIDDLE-QUIZ' => 'AmpRiddleQuiz',
        'SCRIPT (amp-script)' => 'ScriptAmpScript',
        'amp-script extension local script' => 'AmpScriptExtensionLocalScript',
        'AMP-SCRIPT' => 'AmpScript',
        'CANVAS' => 'Canvas',
        'SCRIPT (amp-selector)' => 'ScriptAmpSelector',
        'SCRIPT[custom-element=amp-selector] (AMP4EMAIL)' => 'ScriptCustomElementAmpSelectorAmp4email',
        'AMP-SELECTOR' => 'AmpSelector',
        'AMP-SELECTOR option' => 'AmpSelectorOption',
        'AMP-SELECTOR child' => 'AmpSelectorChild',
        'SCRIPT (amp-sidebar)' => 'ScriptAmpSidebar',
        'SCRIPT[custom-element=amp-sidebar] (AMP4EMAIL)' => 'ScriptCustomElementAmpSidebarAmp4email',
        'amp-sidebar' => 'AmpSidebar',
        'amp-sidebar (AMP4EMAIL)' => 'AmpSidebarAmp4email',
        'amp-story >> amp-sidebar' => 'AmpStoryAmpSidebar',
        'amp-sidebar > nav' => 'AmpSidebarNav',
        'SCRIPT (amp-skimlinks)' => 'ScriptAmpSkimlinks',
        'AMP-SKIMLINKS' => 'AmpSkimlinks',
        'SCRIPT (amp-slides)' => 'ScriptAmpSlides',
        'SCRIPT (amp-smartlinks)' => 'ScriptAmpSmartlinks',
        'AMP-SMARTLINKS' => 'AmpSmartlinks',
        'SCRIPT (amp-social-share)' => 'ScriptAmpSocialShare',
        'AMP-SOCIAL-SHARE' => 'AmpSocialShare',
        'SCRIPT (amp-soundcloud)' => 'ScriptAmpSoundcloud',
        'AMP-SOUNDCLOUD' => 'AmpSoundcloud',
        'SCRIPT (amp-springboard-player)' => 'ScriptAmpSpringboardPlayer',
        'AMP-SPRINGBOARD-PLAYER' => 'AmpSpringboardPlayer',
        'SCRIPT (amp-sticky-ad)' => 'ScriptAmpStickyAd',
        'AMP-STICKY-AD' => 'AmpStickyAd',
        'SCRIPT (amp-story-360)' => 'ScriptAmpStory360',
        'AMP-STORY-360' => 'AmpStory360',
        'SCRIPT (amp-story-auto-ads)' => 'ScriptAmpStoryAutoAds',
        'AMP-STORY-AUTO-ADS' => 'AmpStoryAutoAds',
        'amp-story-auto-ads config script' => 'AmpStoryAutoAdsConfigScript',
        'amp-story-auto-ads > template' => 'AmpStoryAutoAdsTemplate',
        'SCRIPT (amp-story-interactive)' => 'ScriptAmpStoryInteractive',
        'AMP-STORY-INTERACTIVE-QUIZ' => 'AmpStoryInteractiveQuiz',
        'AMP-STORY-INTERACTIVE-POLL' => 'AmpStoryInteractivePoll',
        'AMP-STORY-INTERACTIVE-BINARY-POLL' => 'AmpStoryInteractiveBinaryPoll',
        'AMP-STORY-INTERACTIVE-RESULTS' => 'AmpStoryInteractiveResults',
        'SCRIPT (amp-story-panning-media)' => 'ScriptAmpStoryPanningMedia',
        'AMP-STORY-PANNING-MEDIA' => 'AmpStoryPanningMedia',
        'SCRIPT (amp-story-player)' => 'ScriptAmpStoryPlayer',
        'AMP-STORY-PLAYER' => 'AmpStoryPlayer',
        'SCRIPT (amp-story)' => 'ScriptAmpStory',
        'AMP-STORY' => 'AmpStory',
        'AMP-STORY-PAGE' => 'AmpStoryPage',
        'AMP-STORY-GRID-LAYER' => 'AmpStoryGridLayer',
        'AMP-STORY-GRID-LAYER default' => 'AmpStoryGridLayerDefault',
        'AMP-STORY-GRID-LAYER animate-in' => 'AmpStoryGridLayerAnimateIn',
        'AMP-STORY-BOOKEND' => 'AmpStoryBookend',
        'amp-story-bookend extension .json script' => 'AmpStoryBookendExtensionJsonScript',
        'amp-story-consent extension .json script' => 'AmpStoryConsentExtensionJsonScript',
        'AMP-STORY-CONSENT' => 'AmpStoryConsent',
        'AMP-STORY-CTA-LAYER' => 'AmpStoryCtaLayer',
        'amp-experiment story extension .json script' => 'AmpExperimentStoryExtensionJsonScript',
        'AMP-STORY-CTA-LAYER animate-in' => 'AmpStoryCtaLayerAnimateIn',
        'amp-story-page-attachment[href]' => 'AmpStoryPageAttachmentHref',
        'amp-story-page-attachment' => 'AmpStoryPageAttachment',
        'amp-story-animation json script' => 'AmpStoryAnimationJsonScript',
        'AMP-STORY-ANIMATION' => 'AmpStoryAnimation',
        'meta name=amp-story-generator-name' => 'MetaNameAmpStoryGeneratorName',
        'meta name=amp-story-generator-version' => 'MetaNameAmpStoryGeneratorVersion',
        'SCRIPT (amp-subscriptions)' => 'ScriptAmpSubscriptions',
        'amp-subscriptions extension .json script' => 'AmpSubscriptionsExtensionJsonScript',
        'SCRIPT (amp-subscriptions-google)' => 'ScriptAmpSubscriptionsGoogle',
        'cryptokeys .json script' => 'CryptokeysJsonScript',
        'subscriptions-section content swg_amp_cache_nonce' => 'SubscriptionsSectionContentSwgAmpCacheNonce',
        'subscriptions script ciphertext' => 'SubscriptionsScriptCiphertext',
        'span swg_amp_cache_nonce' => 'SpanSwgAmpCacheNonce',
        'SCRIPT (amp-timeago)' => 'ScriptAmpTimeago',
        'SCRIPT[custom-element=amp-timeago] (AMP4EMAIL)' => 'ScriptCustomElementAmpTimeagoAmp4email',
        'AMP-TIMEAGO' => 'AmpTimeago',
        'SCRIPT (amp-truncate-text)' => 'ScriptAmpTruncateText',
        'AMP-TRUNCATE-TEXT' => 'AmpTruncateText',
        'SCRIPT (amp-twitter)' => 'ScriptAmpTwitter',
        'AMP-TWITTER' => 'AmpTwitter',
        'SCRIPT (amp-user-notification)' => 'ScriptAmpUserNotification',
        'AMP-USER-NOTIFICATION' => 'AmpUserNotification',
        'SCRIPT (amp-video-docking)' => 'ScriptAmpVideoDocking',
        'SCRIPT (amp-video-iframe)' => 'ScriptAmpVideoIframe',
        'AMP-VIDEO-IFRAME[poster]' => 'AmpVideoIframePoster',
        'AMP-VIDEO-IFRAME with [placeholder]' => 'AmpVideoIframeWithPlaceholder',
        'AMP-VIDEO-IFRAME with [placeholder] (transformed)' => 'AmpVideoIframeWithPlaceholderTransformed',
        'AMP-VIDEO-IFRAME > [placeholder]' => 'AmpVideoIframePlaceholder',
        'AMP-VIDEO-IFRAME > I-AMPHTML-SIZER [style]' => 'AmpVideoIframeIAmphtmlSizerStyle',
        'amp-video extension script' => 'AmpVideoExtensionScript',
        'AMP-VIDEO' => 'AmpVideo',
        'amp-story >> amp-story-page-attachment >> amp-video' => 'AmpStoryAmpStoryPageAttachmentAmpVideo',
        'amp-story >> amp-video' => 'AmpStoryAmpVideo',
        'SCRIPT (amp-vimeo)' => 'ScriptAmpVimeo',
        'AMP-VIMEO' => 'AmpVimeo',
        'SCRIPT (amp-vine)' => 'ScriptAmpVine',
        'AMP-VINE' => 'AmpVine',
        'SCRIPT (amp-viqeo-player)' => 'ScriptAmpViqeoPlayer',
        'AMP-VIQEO-PLAYER' => 'AmpViqeoPlayer',
        'SCRIPT (amp-vk)' => 'ScriptAmpVk',
        'AMP-VK' => 'AmpVk',
        'SCRIPT (amp-web-push)' => 'ScriptAmpWebPush',
        'AMP-WEB-PUSH' => 'AmpWebPush',
        'AMP-WEB-PUSH-WIDGET' => 'AmpWebPushWidget',
        'SCRIPT (amp-wistia-player)' => 'ScriptAmpWistiaPlayer',
        'AMP-WISTIA-PLAYER' => 'AmpWistiaPlayer',
        'SCRIPT (amp-yotpo)' => 'ScriptAmpYotpo',
        'AMP-YOTPO' => 'AmpYotpo',
        'SCRIPT (amp-youtube)' => 'ScriptAmpYoutube',
        'AMP-YOUTUBE' => 'AmpYoutube',
    ];

    /** @var array<Tag> */
    private $tagsCache;

    /** @var array<array> */
    private $byTagName;

    /** @var array */
    private $bySpecName;

    /** @var array<array> */
    private $byFormat;

    /**
     * Get a collection of tags by tag name.
     *
     * @param string $tagName Tag name to get the collection of tags for.
     * @return array<Tag> Array of tags. Empty array if tag name not found.
     */
    public function byTagName($tagName)
    {
        $tagName = strtolower($tagName);

        if (!array_key_exists($tagName, $this->byTagName)) {
            return [];
        }

        $tagIds = $this->byTagName[$tagName];
        if (!is_array($tagIds)) {
            $tagIds = [$tagIds];
        }

        $tags = [];
        foreach ($tagIds as $tagId) {
            $tags[$tagId] = $this->byTagId($tagId);
        }

        return $tags;
    }

    /**
     * Get the tag for a given spec name.
     *
     * @param string $specName Spec name to get the tag for.
     * @return Tag Tag with the given spec name.
     * @throws InvalidSpecName If an invalid spec name is requested.
     */
    public function bySpecName($specName)
    {
        if (!array_key_exists($specName, $this->bySpecName)) {
            throw \AmpProject\Exception\InvalidSpecName::forSpecName($specName);
        }

        return $this->bySpecName[$specName];
    }

    /**
     * Get a collection of tags for a given AMP HTML format name.
     *
     * @param string $format AMP HTML format to get the tags for.
     * @return array<Tag> Array of tags matching the requested AMP HTML format.
     * @throws InvalidSpecName If an invalid AMP HTML format is requested.
     */
    public function byFormat($format)
    {
        if (!array_key_exists($format, $this->byFormat)) {
            throw \AmpProject\Exception\InvalidFormat::forFormat($format);
        }

        $tags = $this->byFormat[$format];
        return is_array($tags) ? $tags : [$tags];
    }

    /**
     * Get a tag by its tag ID.
     *
     * @param string $tagId Tag ID for which to get the tag.
     * @return Tag Tag object.
     */
    public function byTagId($tagId)
    {
        if (array_key_exists($tagId, $this->tagsCache)) {
            return $this->tagsCache[$tagId];
        }

        if (!array_key_exists($tagId, self::TAGS)) {
            throw \AmpProject\Exception\InvalidTagId::forTagId($tagId);
        }

        $tagClassName = self::TAGS[$tagId];
        $tag          = new $tagClassName();

        $this->tagsCache[$tagId] = $tag;

        return $tag;
    }
}
